### ISSUE TITLE
Implement all the database tables and constraints.

### ISSUE THREAD

**Issue by amguinto** [amguinto/CS631_Del3#1]
# TODO:

## 1.) Create database tables in the schema.sql file.

Create comments above each table indicating why you created them, and specify the relationships between each table.

## 2.) Create constraints

This can be done as part of the 
```sql
CREATE TABLE FooTable()
```
query you are creating in part 1.

Similar to part 1, please include comments as to why you included these constraints.
This would help when building the API.

**Comment by Zwhitehall** [comment]
First draft. Let me know if I'm missing anything or what should be removed.
